#!/usr/bin/env python3
"""
PDF to Knowledge Base Converter
แปลงไฟล์ PDF เป็น JavaScript Knowledge Base สำหรับ AI Chatbot
"""

import pdfplumber
import json
import sys
import re
from pathlib import Path

def extract_text_from_pdf(pdf_path):
    """แยกข้อความจาก PDF"""
    text_content = []
    
    try:
        with pdfplumber.open(pdf_path) as pdf:
            print(f"📄 กำลังอ่าน PDF: {pdf_path}")
            print(f"📊 จำนวนหน้า: {len(pdf.pages)}")
            
            for i, page in enumerate(pdf.pages, 1):
                text = page.extract_text()
                if text:
                    text_content.append({
                        'page': i,
                        'content': text.strip()
                    })
                    print(f"✅ อ่านหน้า {i} เสร็จ ({len(text)} ตัวอักษร)")
                    
        return text_content
    except Exception as e:
        print(f"❌ เกิดข้อผิดพลาด: {e}")
        return None

def parse_zodiac_content(text_content):
    """
    แปลงข้อความจาก PDF เป็นรูปแบบ Knowledge Base
    ปรับแต่งฟังก์ชันนี้ตาม format ของ PDF คุณ
    """
    knowledge = {}
    
    # ตัวอย่าง: สมมติว่า PDF มีข้อมูลในรูปแบบ
    # ราศีเมษ
    # ความรัก: ...
    # การงาน: ...
    
    current_zodiac = None
    current_section = None
    
    for page_data in text_content:
        content = page_data['content']
        lines = content.split('\n')
        
        for line in lines:
            line = line.strip()
            if not line:
                continue
            
            # ตรวจหาชื่อราศี
            zodiac_names = ['เมษ', 'พฤษภ', 'เมถุน', 'กรกฎ', 'สิงห์', 'กันย์', 
                          'ตุลย์', 'พิจิก', 'ธนู', 'มังกร', 'กุมภ์', 'มีน']
            
            for zodiac in zodiac_names:
                if zodiac in line:
                    current_zodiac = zodiac
                    if current_zodiac not in knowledge:
                        knowledge[current_zodiac] = {}
                    break
            
            # ตรวจหาหัวข้อ
            if current_zodiac:
                if 'ความรัก' in line or 'รัก' in line:
                    current_section = 'love'
                elif 'การงาน' in line or 'งาน' in line:
                    current_section = 'career'
                elif 'การเงิน' in line or 'เงิน' in line:
                    current_section = 'finance'
                elif 'สุขภาพ' in line:
                    current_section = 'health'
                
                # เก็บข้อมูล
                if current_section and len(line) > 20:  # ข้อความยาวพอสมควร
                    if current_section not in knowledge[current_zodiac]:
                        knowledge[current_zodiac][current_section] = []
                    knowledge[current_zodiac][current_section].append(line)
    
    return knowledge

def convert_to_javascript(knowledge, output_file):
    """แปลงเป็น JavaScript format"""
    
    js_content = """// Auto-generated Knowledge Base from PDF
// Generated by pdf_to_knowledge.py

const pdfKnowledge = """
    
    # แปลง dict เป็น JSON
    js_content += json.dumps(knowledge, ensure_ascii=False, indent=4)
    
    js_content += """;

// Helper function to get knowledge
function getKnowledgeByZodiac(zodiacName) {
    return pdfKnowledge[zodiacName] || null;
}

// Export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { pdfKnowledge, getKnowledgeByZodiac };
}
"""
    
    # บันทึกไฟล์
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"\n✅ สร้างไฟล์ {output_file} เสร็จสิ้น!")
    return True

def main():
    if len(sys.argv) < 2:
        print("❌ กรุณาระบุชื่อไฟล์ PDF")
        print(f"วิธีใช้: python {sys.argv[0]} <ไฟล์.pdf>")
        print(f"ตัวอย่าง: python {sys.argv[0]} zodiac_data.pdf")
        sys.exit(1)
    
    pdf_path = sys.argv[1]
    
    if not Path(pdf_path).exists():
        print(f"❌ ไม่พบไฟล์: {pdf_path}")
        sys.exit(1)
    
    # แยกข้อความจาก PDF
    print("\n🚀 เริ่มแปลงไฟล์...")
    text_content = extract_text_from_pdf(pdf_path)
    
    if not text_content:
        print("❌ ไม่สามารถแยกข้อความจาก PDF ได้")
        sys.exit(1)
    
    # บันทึกข้อความดิบ (สำหรับตรวจสอบ)
    raw_output = "pdf_raw_text.json"
    with open(raw_output, 'w', encoding='utf-8') as f:
        json.dump(text_content, f, ensure_ascii=False, indent=2)
    print(f"\n💾 บันทึกข้อความดิบไว้ที่: {raw_output}")
    
    # แปลงเป็น Knowledge Base
    print("\n🔄 กำลังแปลงเป็น Knowledge Base...")
    knowledge = parse_zodiac_content(text_content)
    
    if not knowledge:
        print("⚠️  ไม่พบข้อมูลที่สามารถแปลงได้")
        print("💡 ตรวจสอบ pdf_raw_text.json และปรับแต่งฟังก์ชัน parse_zodiac_content()")
        sys.exit(1)
    
    # แปลงเป็น JavaScript
    output_file = "../js/data/pdf-knowledge.js"
    convert_to_javascript(knowledge, output_file)
    
    print(f"\n📊 สถิติ:")
    print(f"   - จำนวนราศี: {len(knowledge)}")
    for zodiac, data in knowledge.items():
        print(f"   - {zodiac}: {len(data)} หัวข้อ")
    
    print("\n✨ เสร็จสิ้น! ไฟล์พร้อมใช้งาน")
    print(f"📁 ไฟล์ที่สร้าง: {output_file}")
    print("\n💡 ขั้นตอนต่อไป:")
    print("   1. ตรวจสอบไฟล์ js/data/pdf-knowledge.js")
    print("   2. เพิ่ม <script src='js/data/pdf-knowledge.js'></script> ใน chatbot.html")
    print("   3. อัปเดท chatbot.js ให้ดึงข้อมูลจาก pdfKnowledge")

if __name__ == "__main__":
    main()
